// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! Aggregate-function registration.
//!
//! Phase 3c (2026-06-24): wired via rusqlite's
//! `Connection::create_aggregate_function`. Each shim
//! AggregateFunctionDef becomes one ShimAggregate instance
//! registered under every canonical + alias name.
//!
//! State plumbing:
//!   - rusqlite's Aggregate<A, T> trait: A is the per-group
//!     accumulator type, T is the SQL return value (must
//!     impl ToSql). We use A = AccState (newtype around
//!     Box<dyn Accumulator>) and T = ToSqlOutput<'static>.
//!   - rusqlite requires A: RefUnwindSafe + UnwindSafe. The
//!     shim's Accumulator trait doesn't promise either, so
//!     AccState manually opts in (correctness rests on the
//!     shim not panicking on accumulate/finalize — its
//!     wasm-side impl uses Result, no unwinds expected).

use std::panic::{RefUnwindSafe, UnwindSafe};
use std::sync::Arc;

use rusqlite::functions::{Aggregate, Context, FunctionFlags};
use rusqlite::types::{ToSqlOutput, Value};
use rusqlite::{Connection, Result};

use datafission_functions::traits::{Accumulator, AggregateFunctionDef};
use datafission_functions::types::FunctionValue;

use crate::registry;
use crate::scalars::{function_value_to_tosql, value_ref_to_function_value};

/// Per-group accumulator state with the UnwindSafe opt-in that
/// rusqlite requires on `A`.
struct AccState(Box<dyn Accumulator>);
impl RefUnwindSafe for AccState {}
impl UnwindSafe for AccState {}

/// Stateless dispatcher: the per-group state lives in `AccState`,
/// not in this struct. One instance per (name × registration).
struct ShimAggregate {
    def: Arc<dyn AggregateFunctionDef>,
}

impl Aggregate<AccState, ToSqlOutput<'static>> for ShimAggregate {
    fn init(&self, _ctx: &mut Context<'_>) -> Result<AccState> {
        Ok(AccState(self.def.create_accumulator()))
    }

    fn step(&self, ctx: &mut Context<'_>, acc: &mut AccState) -> Result<()> {
        // PostGIS aggregates are unary (ST_Union, ST_Extent,
        // ST_Collect — all take one geometry). For multi-arg
        // future aggregates: walk every ctx arg and call
        // accumulate per row's input tuple. The Accumulator
        // trait takes one value per accumulate call.
        let n = ctx.len();
        if n == 0 {
            return Ok(());
        }
        let v = ctx.get_raw(0);
        // NULL convention: SQL-92 aggregates skip NULL inputs
        // (except COUNT(*)). The shim's Accumulator may also
        // skip; pass NULL through and let the shim decide.
        let value = value_ref_to_function_value(v);
        acc.0.accumulate(&value).map_err(|e| {
            rusqlite::Error::UserFunctionError(Box::new(std::io::Error::other(format!("{e:?}"))))
        })
    }

    fn finalize(
        &self,
        _ctx: &mut Context<'_>,
        acc: Option<AccState>,
    ) -> Result<ToSqlOutput<'static>> {
        match acc {
            Some(a) => {
                let result = a.0.finalize().map_err(|e| {
                    rusqlite::Error::UserFunctionError(Box::new(std::io::Error::other(format!(
                        "{e:?}"
                    ))))
                })?;
                Ok(function_value_to_tosql(result))
            }
            None => {
                // No rows accumulated → SQL aggregates return NULL.
                // (Except COUNT, which would return 0 — but that
                // never reaches this branch in practice.)
                let _ = self;
                let _ = FunctionValue::Null;
                Ok(ToSqlOutput::Owned(Value::Null))
            }
        }
    }
}

/// Register every aggregate the shim publishes.
pub fn register_all(conn: &Connection) -> Result<()> {
    register_aggregate(conn, "st_3dextent", 1)?;
    register_aggregate(conn, "st_3d_extent", 1)?; // alias of st_3dextent
    register_aggregate(conn, "st_clusterdbscan", 3)?;
    register_aggregate(conn, "st_cluster_dbscan", 3)?; // alias of st_clusterdbscan
    register_aggregate(conn, "st_clusterintersecting", 1)?;
    register_aggregate(conn, "st_cluster_intersecting", 1)?; // alias of st_clusterintersecting
    register_aggregate(conn, "st_cluster_intersecting_aggregate", 1)?; // alias of st_clusterintersecting
    register_aggregate(conn, "st_clusterintersectingaggregate", 1)?; // alias of st_clusterintersecting
    register_aggregate(conn, "st_clusterwithin", 2)?;
    register_aggregate(conn, "st_cluster_within", 2)?; // alias of st_clusterwithin
    register_aggregate(conn, "st_cluster_within_aggregate", 2)?; // alias of st_clusterwithin
    register_aggregate(conn, "st_clusterwithinaggregate", 2)?; // alias of st_clusterwithin
    register_aggregate(conn, "st_collect", 1)?;
    register_aggregate(conn, "st_coverageunion", 1)?;
    register_aggregate(conn, "st_coverage_union", 1)?; // alias of st_coverageunion
    register_aggregate(conn, "st_extent", 1)?;
    register_aggregate(conn, "st_makeline", 1)?;
    register_aggregate(conn, "st_make_line", 1)?; // alias of st_makeline
    register_aggregate(conn, "st_make_line_aggregate", 1)?; // alias of st_makeline
    register_aggregate(conn, "st_makelineagg", 1)?; // alias of st_makeline
    register_aggregate(conn, "st_makelineaggregate", 1)?; // alias of st_makeline
    register_aggregate(conn, "st_polygonize", 1)?;
    register_aggregate(conn, "st_polygonize_aggregate", 1)?; // alias of st_polygonize
    register_aggregate(conn, "st_polygonizeagg", 1)?; // alias of st_polygonize
    register_aggregate(conn, "st_polygonizeaggregate", 1)?; // alias of st_polygonize
    register_aggregate(conn, "st_rast_union", 1)?;
    register_aggregate(conn, "st_rast_union_aggregate", 1)?; // alias of st_rast_union
    register_aggregate(conn, "st_raster_union", 1)?; // alias of st_rast_union
    register_aggregate(conn, "st_union", 1)?;
    register_aggregate(conn, "st_mem_union", 1)?; // alias of st_union
    register_aggregate(conn, "st_memunion", 1)?; // alias of st_union
    register_aggregate(conn, "st_union_aggregate", 1)?; // alias of st_union
    register_aggregate(conn, "st_unionagg", 1)?; // alias of st_union
    register_aggregate(conn, "st_unionaggregate", 1)?; // alias of st_union
                                                       // Phase 3c: 11 canonical + 23 alias names registered.
    Ok(())
}

fn register_aggregate(conn: &Connection, sql_name: &str, arity: i32) -> Result<()> {
    let def = registry::lookup_aggregate(sql_name).ok_or_else(|| {
        rusqlite::Error::UserFunctionError(
            format!("aggregate `{sql_name}` not registered by the shim").into(),
        )
    })?;
    conn.create_aggregate_function(
        sql_name,
        arity,
        FunctionFlags::SQLITE_DETERMINISTIC | FunctionFlags::SQLITE_UTF8,
        ShimAggregate { def },
    )
}
