// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! CAST(x AS T) rewrites.
//!
//! ## Phase 4d — same blocker as operators.
//!
//! SQLite's `CAST(x AS GEOMETRY)` is parser-level — the type
//! name is consumed as a built-in token and converted at parse
//! time. There is no hook for a custom-type CAST. We cannot
//! rewrite `CAST(x AS GEOMETRY)` → `st_geomfromtext(x)` from
//! inside a loadable extension; the parse fails first.
//!
//! The proper home for cast rewrites is the same separate
//! `sqlink-preprocess` crate documented in operators.rs.

use rusqlite::{Connection, Result};

pub fn register_all(_conn: &Connection) -> Result<()> {
    Ok(())
}

// ----------------------------------------------------------------------
// Cast rewrites the shim advertises.
// ----------------------------------------------------------------------

// === extension: postgis ===
// CAST(<castsourcekind::any> AS box2d) → st_envelope (hint: )
// CAST(<castsourcekind::stringliteral> AS geography) → st_geogfromtext (hint: )
// CAST(<castsourcekind::geographycolumn> AS geometry) → st_geogtogeom (hint: )
// CAST(<castsourcekind::stringliteral> AS geometry) → st_geomfromtext (hint: )
