// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! Generated SQLite extension entry point.
//!
//! Load with:
//!   sqlite> .load ./target/release/lib<ext>_sqlite_bridge
//!
//! Phase 1 (2026-06-23): scalar dispatch wired through
//! df-plugin-loader. ST_GeomFromText is fully functional; the
//! other categories (aggregates, UDTFs, window funcs, types,
//! operators, casts, preprocessors, system catalog, spatial
//! indexes) are scaffold-only — see per-module TODOs and
//! AGENTS.md for the phased plan.

pub mod registry;
pub mod scalars;
pub mod aggregates;
pub mod table_functions;
pub mod window_functions;
pub mod types;
pub mod operators;
pub mod casts;
pub mod preprocessors;
pub mod system_catalog;
pub mod spatial_indexes;

use std::os::raw::{c_char, c_int};

use rusqlite::ffi;
use rusqlite::{Connection, Result};

/// SQLite extension entry point. Loaded by SQLite when the
/// user runs `.load`. rusqlite's `extension_init2` wraps the
/// `SQLITE_EXTENSION_INIT2` macro: it stashes the api routines
/// pointer and hands us a safe `Connection`.
///
/// Symbol name must be `sqlite3_extension_init` for the
/// default `.load` behavior (no explicit init-function name).
#[allow(clippy::not_unsafe_ptr_arg_deref)]
#[no_mangle]
pub unsafe extern "C" fn sqlite3_extension_init(
    db: *mut ffi::sqlite3,
    pz_err_msg: *mut *mut c_char,
    p_api: *mut ffi::sqlite3_api_routines,
) -> c_int {
    Connection::extension_init2(db, pz_err_msg, p_api, init_inner)
}

fn init_inner(conn: Connection) -> Result<bool> {
    // Load the composed shim wasm exactly once. The path comes
    // from `<EXT>_SHIM_WASM` env var so the bridge isn't pinned
    // to a build-time path (matches the host's runtime-loaded
    // model).
    registry::load_shim().map_err(|e| {
        // `{e:#}` walks the anyhow chain so the user sees the
        // underlying cause (wasm parse error, missing import,
        // etc.) rather than just the top-level wrapper.
        rusqlite::Error::UserFunctionError(
            format!("shim load: {e:#}").into()
        )
    })?;

    // Register scalars (Phase 2) + aggregates (Phase 3c).
    scalars::register_all(&conn)
        .map_err(|e| rusqlite::Error::UserFunctionError(
            format!("scalar registration: {e}").into()
        ))?;
    aggregates::register_all(&conn)
        .map_err(|e| rusqlite::Error::UserFunctionError(
            format!("aggregate registration: {e}").into()
        ))?;
    table_functions::register_all(&conn)
        .map_err(|e| rusqlite::Error::UserFunctionError(
            format!("table function registration: {e}").into()
        ))?;

    // Returning `true` means "extension fully initialized — no
    // need to keep it loaded across DB sessions". `false` would
    // ask SQLite to auto-load on every new connection in the
    // process.
    Ok(true)
}

// Extensions loaded by this bridge:
//
//   - postgis v0.1.0  (402 scalars, 11 agg, 7 udtf, 4 window, 7 types, 23 ops, 4 casts, 1 preps, 0 catalog, 9 indexes)
