// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! Operator handling.
//!
//! ## Phase 4d — ARCHITECTURALLY BLOCKED for a loadable
//! extension (2026-06-24)
//!
//! Operators like `g1 && g2` and `g1 <-> g2` are PARSER-LEVEL
//! tokens in PostgreSQL. SQLite's parser does not recognise
//! them — `SELECT g1 && g2` is a syntax error BEFORE any
//! function dispatch could intervene. There is no SQLite C
//! API to register a custom operator token.
//!
//! Loadable extensions cannot fix this. The bridge can register
//! a normal scalar function under any name, but the SQL parser
//! is fixed.
//!
//! ## Where this work actually lives
//!
//! Operator/cast/preprocessor support is a SQL-PREPROCESSING
//! concern, not an extension concern. The proper home is a
//! separate `sqlink-preprocess` crate that:
//!
//!   - Parses the SQL surface (via sqlparser-rs)
//!   - Rewrites operators: `g1 && g2` → `st_bboxintersects(g1, g2)`
//!   - Rewrites casts:     `CAST(x AS GEOMETRY)` → `st_geomfromtext(x)`
//!     when x is a string literal
//!   - Hands the rewritten SQL to rusqlite's `prepare`/`execute`
//!
//! That crate doesn't ship as a SQLite extension — it's a host-
//! side library users wrap their SQL with. It can absolutely be
//! generated from the same `BridgePlan` this crate emits, but
//! it's a separate target crate.
//!
//! ## The bridge-side compromise
//!
//! For users who don't want to wrap their SQL, the bridge could
//! register the operator NAMES as regular scalars under encoded
//! names:
//!
//!   register_scalar("op_amp_amp",   ...) → st_bboxintersects
//!   register_scalar("op_arrow",     ...) → st_knndistance
//!   register_scalar("op_at_gt",     ...) → st_contains
//!
//! Users write `op_amp_amp(g1, g2)` instead of `g1 && g2`. It
//! works (a function with that name is fine in SQLite) but it's
//! syntactically ugly. Not currently emitted — flip on by
//! removing the early return below.

use rusqlite::{Connection, Result};

pub fn register_all(_conn: &Connection) -> Result<()> {
    // Bridge-side compromise (op_<encoded>(args)) is deliberately
    // off by default. The proper home is sqlink-preprocess (a
    // separate sibling crate that wraps SQL before execute).
    Ok(())
}

// ----------------------------------------------------------------------
// Operators the shim advertises.
// ----------------------------------------------------------------------

// === extension: postgis ===
// `##` (lhs=Some(2001), rhs=Some(2001))  →  st_intersection
// `&&` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxintersects
// `&&` (lhs=Some(2003), rhs=Some(2003))  →  st_intersects
// `&&&` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxintersectsnd
// `&&|` (lhs=Some(2001), rhs=Some(2001))  →  st_intersects
// `&<` (lhs=Some(2001), rhs=Some(2001))  →  st_overlaps
// `&<` (lhs=Some(2003), rhs=Some(2003))  →  st_overlaps
// `&<>` (lhs=Some(2001), rhs=Some(2001))  →  st_disjoint
// `&>` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxoverright
// `<#>` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxdistance
// `<->` (lhs=Some(2001), rhs=Some(2001))  →  st_knndistance
// `<<` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxleftof
// `<<|` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxbelow
// `<@` (lhs=Some(2001), rhs=Some(2001))  →  st_within
// `<@` (lhs=Some(2003), rhs=Some(2003))  →  st_within
// `>>` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxrightof
// `@>` (lhs=Some(2001), rhs=Some(2001))  →  st_contains
// `@>` (lhs=Some(2003), rhs=Some(2003))  →  st_contains
// `|>>` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxabove
// `||` (lhs=Some(2001), rhs=Some(2001))  →  st_union
// `~` (lhs=Some(2001), rhs=Some(2001))  →  st_contains
// `~=` (lhs=Some(2001), rhs=Some(2001))  →  st_geomequal
// `~=` (lhs=Some(2003), rhs=Some(2003))  →  st_equals
