// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! SQL preprocessor patterns — token-level rewrites the shim
//! advertises (e.g. PostGIS's EWKT-shorthand prefix-arrow).
//!
//! ## Phase 4d — same blocker as operators / casts.
//!
//! Token-level rewrites are by definition a parser concern.
//! They cannot be implemented inside a loadable extension. See
//! operators.rs for the architectural picture and the
//! `sqlink-preprocess` proposal.

use rusqlite::{Connection, Result};

pub fn register_all(_conn: &Connection) -> Result<()> {
    Ok(())
}

// ----------------------------------------------------------------------
// Preprocessor patterns the shim advertises.
// ----------------------------------------------------------------------

// === extension: postgis ===
// token `~` → __pg_contains__
