// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! Spatial index registration.
//!
//! SQLite has R*Tree (`rtree` module, built in) and nothing
//! else. The bridge maps each shim spatial-index `type_id` to
//! an R*Tree-backed virtual table; SQL `CREATE INDEX … USING
//! <name>` becomes a CREATE VIRTUAL TABLE statement under the
//! hood. Insert/delete triggers keep the rtree in sync.
//!
//! For non-rectangular indexes (KdTree, Quadtree, Octree) the
//! shim's CPU-side query takes over: we register a UDTF
//! `<name>_query(args)` that the optimizer can use when it
//! sees a WHERE clause involving an index-aware operator. See
//! operators.rs for the rewrite that feeds it.

// index `brin` type_id=0
// index `gist` type_id=0
// index `kd-tree` type_id=0
// index `kdtree` type_id=0
// index `rtree` type_id=0
// index `sp-gist` type_id=0
// index `sp_gist` type_id=0
// index `spatial` type_id=0
// index `spgist` type_id=0

// TODO: emit one CREATE VIRTUAL TABLE … USING rtree(...)
//       per shim index, plus the trigger pair that
//       maintains it on the source table.
