// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! System-catalog virtual tables (spatial_ref_sys etc.).
//!
//! Each becomes a sqlite3_module-backed virtual table. The
//! schema is in the comments below; the dispatch pulls rows
//! from the shim's catalog provider.


// TODO: emit sqlite3_create_module_v2 calls for each.
