// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! Custom column types.
//!
//! SQLite does NOT have first-class custom types; the
//! conventional pattern is BLOB columns + a sidecar text-type
//! affinity. GEOMETRY ends up stored as EWKB blobs.
//!
//! The bridge advertises the type names so application code
//! can use `CREATE TABLE t (g GEOMETRY)` syntactically — but
//! SQLite stores it as BLOB. Type-id round-trips through the
//! shim are preserved via the shim's own type tag inside the
//! blob payload.

// type_id= 2001 name=GEOMETRY                 size=  -1  cast_from=[]  cast_to=[]
// type_id= 2002 name=BOX2D                    size=  -1  cast_from=[]  cast_to=[]
// type_id= 2003 name=GEOGRAPHY                size=  -1  cast_from=[]  cast_to=[]
// type_id= 2004 name=RASTER                   size=  -1  cast_from=[]  cast_to=[]
// type_id= 2005 name=VECTOR                   size=  -1  cast_from=[]  cast_to=[]
// type_id= 2006 name=TOPOGEOMETRY             size=  -1  cast_from=[]  cast_to=[]
// type_id= 2007 name=BOX3D                    size=  48  cast_from=[]  cast_to=[]

// TODO: no explicit registration needed for SQLite — types are advisory.
//       Use this list to wire CAST() rewrites in casts.rs.
