// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! Window-function registration (sqlite3_create_window_function).

// window `st_clusterdbscan`
// window `st_clusterintersectingwin`
// window `st_clusterkmeans`
// window `st_clusterwithinwin`

// TODO: emit sqlite3_create_window_function calls.
